### ISSUE TITLE
Care if I tweak and package this up as a Gamebuino META game?

### ISSUE THREAD

**Issue by joshgoebel** [dobragab/snake3310#2]
I see it has a MIT license but just thought I'd ask first.  I'd make sure you had a mention in the credits as the originator.

https://www.kickstarter.com/projects/rodot/gamebuino-meta

**Comment by dobragab** [comment]
You can use it as MIT license allows you. :)

**Comment by joshgoebel** [comment]
Thanks!

**Comment by joshgoebel** [comment]
You just a big Nokia snake fan?  It's very true to the original (as far as I can tell).

**Comment by dobragab** [comment]
You're welcome.

I like recreating the games of my childhood, like this Snake. The intenton was to make it as close to the original as possible, though I lost my patience recreating the intro frames.
