### ISSUE TITLE
Bug with keyboard input (two inputs in rapid succession fail)

### ISSUE THREAD

**Issue by joshgoebel** [dobragab/snake3310#3]
If you care: There is a bug with keyboard input if you issue two command in the same TICK (turn right, then turn right again, etc) they both get dropped.  (or does one get dropped? Now I forget).  I'll likely fix it for my port... 

This was driving me nuts until I tracked it down (worse the slower the snake moves).  Because sometimes it works depending on where in the TICK your keystrokes land... it needs to record a second keystroke (if it doesn't make sense) and reply it [once] on the subsequent tick to see if it makes sense then. At least that's how it seems to me that it should handle things.

Not sure how the original game handled this.

**Comment by dobragab** [comment]
This is annoying for me as well, but we've just rechecked it on the original hardware (a Nokia 3310 device) and the original game handles this exactly the same way.

**Comment by joshgoebel** [comment]
LOL, so no plans to fix then?

**Comment by dobragab** [comment]
No. Anyway, how would you handle them? Putting events in a queue would cause even worse behavior.

**Comment by joshgoebel** [comment]
How so?  I'd just queue one additional keypress.  It's really only "double" combos you have to handle here... quick 180 degree turns... so if someone executes the combo too quickly you just play the first key as it's hit... then play the second key in the next tick. 

Worst case you queue up 1 or 2 keys and then the player regrets them... but too bad I'd say... you can't have it both ways - either you want all the keystrokes to effect gameplay or you don't.

It's possible there is something I'm overlooking but I think it'd work pretty well.
